

CREATE USER C##KASMISATO IDENTIFIED BY KAMISATO;
alter session set "_oracle_script"=true;
CREATE USER KAMISATO IDENTIFIED BY KAMISATO;

GRANT CONNECT, RESOURCE, dba TO KAMISATO;
GRANT UNLIMITED TABLESPACE TO KAMISATO;

ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- REVOKE
-- DROP USER CEUCEDA CASCADE;


CREATE ROLE DESARROLLADOR;
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE,
INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE, SELECT ANY TABLE
TO DESARROLLADOR

SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'DESARROLLADOR';

GRANT DESARROLLADOR TO KAMISATO

